# Generated by generate model command, create_table adds an auto-incrementing id starting at 1
# Do |t| is used where t is the argument for iterating over a collection. e.g map iteration -> map.each do |key, val|
# Timestamps defines 2 additional columns named: created_at & updated_at. These are managed by Rails.

# Using db:migrate will update the schema.rb to include the changes specified in the migrate folder. Ruby class model -> Ruby DSL
class CreateArticles < ActiveRecord::Migration[7.0]
  def change
    create_table :articles do |t|
      t.string :title
      t.text :body

      t.timestamps
    end
  end
end
